In [1]:
import pandas as pd # for data file reading
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures

In [2]:
athlets = np. array([[151, 83], [69, 46], [198, 92], [75,35]])
mean_althlets = np.mean(athlets, axis=0)
standard_deviation_althlets = np.std(athlets, axis=0).tolist()
standard_deviation = np.std(athlets, axis=0)
print("Mean athlets %d" % mean_althlets[0].item())
print("Standard deviation athlets %d" % standard_deviation_althlets[0])
print("Mean events %d" % mean_althlets[1].item())
print("Standard deviation events %d" % standard_deviation_althlets[1])

# We standardize the values of the observations in the two columns()/for the two variables
standardized_data = []
for row in athlets:
    new_athlets = (row[0] - mean_althlets[0]) / standard_deviation_althlets[0]
    new_events = (row[1] - mean_althlets[1]) / standard_deviation_althlets[1]
    standardized_data.append([new_athlets, new_events])
standardized_data = np.array(standardized_data)
print("Standardized data, matrix X not prepended with ones:\n", standardized_data)

# Compute X^T * X, where X needs to be appended with a column of ones
ones = np.ones((standardized_data.shape[0], 1))
data_to_standardize = np.hstack((ones,standardized_data))
matrix_data = data_to_standardize.T @ data_to_standardize       # element for element multiplication: X^T * X
print("X^T * X:\n", matrix_data)

Mean athlets 123
Standard deviation athlets 53
Mean events 64
Standard deviation events 24
Standardized data, matrix X not prepended with ones:
 [[ 0.51466717  0.79063786]
 [-1.00615113 -0.74902534]
 [ 1.38635571  1.16515053]
 [-0.89487175 -1.20676305]]
X^T * X:
 [[4.00000000e+00 0.00000000e+00 2.22044605e-16]
 [0.00000000e+00 4.00000000e+00 3.85575929e+00]
 [2.22044605e-16 3.85575929e+00 4.00000000e+00]]


In [7]:
A = [80, 60, 50, 40, 20, 50]
B= [40, 80, 70, 70, 90, 70]

cov_matrix = np.cov(A,B)
print(cov_matrix)

[[ 400. -280.]
 [-280.  280.]]


In [42]:
log_0_36 = np.log2(0.58)
print(log_0_36)
x= log_0_36 * 0.58
print(x) 

log_0_63 = np.log2(0.42)
print(log_0_63)
y = log_0_63 * 0.42
print(y)

result = -(x+y)
print("Result: ", result)

-0.7858751946471527
-0.45580761289534855
-1.2515387669959646
-0.5256462821383051
Result:  0.9814538950336537


In [15]:
check = ((1/12) * 1) + ((11/12) * 0.946) 
print(check)

0.9505
